[project]
name = "functionalthreading"
version = "1.0.2"
authors = [
  { name="Richard Tong", email="richytong@gmail.com" },
]
description = "Concurrent functional programming with thread-based parallelism"
readme = "README.md"
requires-python = ">=3.14"
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
]
license = "Unlicense"
license-files = ["LICENSE"]

[project.urls]
Repository = "https://github.com/richytong/functionalthreading"
Issues = "https://github.com/richytong/functionalthreading/issues"
